drivers: gpio: amlogic: properly use binary AND instead of multiplication
With gcc-linaro-7.4.1 this was leading to the following warning and thus error:

  ../drivers/gpio/amlogic_gpio.c: In function ‘aml_gpio_get_function’:
  ../drivers/gpio/amlogic_gpio.c:69:20: error: ‘*’ in boolean context, suggest ‘&&’ instead [-Werror=int-in-bool-context]
    bool dir = !!(val * BIT(bit));
               ~~~~~^~~~~~~~~~~
  cc1: all warnings being treated as errors

Signed-off-by: Martin Pietryka <martin.pietryka@streamunlimited.com>