arch: arm: axg: bl31_apis: un-indent inline asm memory clobber
With gcc-linaro-7.4.1 this was leading to the following warning and thus error:

  ../arch/arm/cpu/armv8/axg/bl31_apis.c:68:2: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
    if (arg->cmd == EFUSE_HAL_API_WRITE)
    ^~
  ../arch/arm/cpu/armv8/axg/bl31_apis.c:71:3: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
     asm __volatile__("" : : : "memory");
     ^~~
  cc1: all warnings being treated as errors

Because of the formatting, the intentions of the original developer are not
100% clear, but just to be on the safe side I moved this memory clobber
outside of the if.

Quote (https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html):
  Using the "memory" clobber effectively forms a read/write memory barrier
  for the compiler.

Signed-off-by: Martin Pietryka <martin.pietryka@streamunlimited.com>